create or replace TABLE SUPPORT_DB.SECURITY.SVC_ACC_OWNER_MAPPING (
	MAPPING_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	OWNER_USER VARCHAR(255) NOT NULL,
	SERVICE_USER VARCHAR(255) NOT NULL,
	ACTIVE VARCHAR(1) NOT NULL DEFAULT 'Y',
	CREATED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(255) NOT NULL,
	UPDATED_ON TIMESTAMP_LTZ(9),
	UPDATED_BY VARCHAR(255),
	unique (OWNER_USER, SERVICE_USER),
	primary key (MAPPING_ID)
);


create or replace TABLE SUPPORT_DB.SECURITY.PAT_ACTIVITY_LOG (
	ACTIVITY_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EVENT_TIME TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	OWNER_USER VARCHAR(255) NOT NULL,
	SERVICE_USER VARCHAR(255) NOT NULL,
	ACTION VARCHAR(20) NOT NULL,
	TOKEN_NAME VARCHAR(255),
	TOKEN_CREATED_ON TIMESTAMP_LTZ(9),
	TOKEN_EXPIRES_ON TIMESTAMP_LTZ(9),
	RESULT VARCHAR(20) NOT NULL,
	ERROR_MESSAGE VARCHAR(2000),
	REQUEST_ID VARCHAR(100),
	primary key (ACTIVITY_ID)
);
